# Generated by Django 4.0.8 on 2022-11-04 19:56
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatever",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
