# Generated by Django 4.0.8 on 2022-11-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_whatever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='whatever',
        ),
    ]
