# Generated by Django 4.0.5 on 2022-07-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urn_li_share', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('click_count', models.PositiveIntegerField(null=True)),
                ('comment_count', models.PositiveIntegerField(null=True)),
                ('engagement', models.FloatField(null=True)),
                ('impression_count', models.PositiveIntegerField(null=True)),
                ('like_count', models.PositiveIntegerField(null=True)),
                ('share_count', models.PositiveIntegerField(null=True)),
            ],
        )
    ]
