# Generated by Django 4.0.5 on 2022-07-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
