# Generated by Django 4.0.5 on 2022-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_largesocialpost_scheduledlargesocialpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LargeSocialPost',
        ),
        migrations.DeleteModel(
            name='ScheduledLargeSocialPost',
        ),
        migrations.AlterField(
            model_name='regularsocialpost',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='scheduledsocialpost',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
