# Generated by Django 4.0.5 on 2022-07-16 19:23

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0003_remove_regularsocialpost_image_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regularsocialpost",
            name="promote",
        ),
        migrations.RemoveField(
            model_name="scheduledsocialpost",
            name="promote",
        ),
    ]
