# Generated by Django 4.0.5 on 2022-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_regularsocialpost_created_regularsocialpost_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.SmallIntegerField(blank=True, choices=[(1, 'Blog post promotion'), (2, 'Regular social post promotion'), (3, 'Scheduled social post promotion'), (4, 'Scheduled social post promotion')], null=True)),
                ('linkedin_id', models.CharField(max_length=20)),
                ('likes', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='regularsocialpost',
            name='promote_in_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularsocialpost',
            name='promote_in_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularsocialpost',
            name='promote_in_linkedin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regularsocialpost',
            name='promote_in_telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regularsocialpost',
            name='promote_in_twitter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduledsocialpost',
            name='promote_in_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledsocialpost',
            name='promote_in_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduledsocialpost',
            name='promote_in_linkedin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduledsocialpost',
            name='promote_in_telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduledsocialpost',
            name='promote_in_twitter',
            field=models.BooleanField(default=True),
        ),
    ]
