# Generated by Django 4.0.5 on 2022-07-16 20:24

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0004_remove_regularsocialpost_promote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinpost",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted after clicking on Save",
                verbose_name="Delete from Linkedin",
            ),
        ),
        migrations.AddField(
            model_name="linkedinpost",
            name="api_deleted",
            field=models.BooleanField(
                default=False, verbose_name="Already deleted from Linkedin"
            ),
        ),
        migrations.AlterField(
            model_name="telegrammessage",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted after clicking on Save",
                verbose_name="Delete from Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted after clicking on Save",
                verbose_name="Delete from Twitter",
            ),
        ),
    ]
