# Generated by Django 4.0.5 on 2022-07-17 15:07

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0006_facebookpost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facebookpost",
            old_name="post_id",
            new_name="facebook_id",
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted after clicking on Save",
                verbose_name="Delete from Facebook",
            ),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="api_deleted",
            field=models.BooleanField(
                default=False, verbose_name="Already deleted from Facebook"
            ),
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="text",
            field=models.TextField(default="Standard text", max_length=1000),
            preserve_default=False,
        ),
    ]
