# Generated by Django 4.0.5 on 2022-07-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_tweet_twitter_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
                ('link', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=4000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
