# Generated by Django 4.0.5 on 2022-07-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0008_facebookpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpost',
            name='facebook_id',
            field=models.CharField(max_length=50),
        ),
    ]
