# Generated by Django 4.0.5 on 2022-07-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0009_telegrammessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='api_delete',
            field=models.BooleanField(default=False, verbose_name='Delete from Telegram'),
        ),
    ]
