# Generated by Django 4.0.5 on 2022-07-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0012_tweet_api_delete_tweet_api_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularsocialpost',
            name='promote',
        ),
        migrations.RemoveField(
            model_name='scheduledsocialpost',
            name='promote',
        ),
    ]
