# Generated by Django 4.0.5 on 2022-07-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0017_alter_tweet_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tweet',
            table='socialmedia_tweets',
        ),
    ]
