# Generated by Django 4.1 on 2022-08-28 11:17

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0017_alter_backgroundimage_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="regularsocialpost",
            old_name="image_background",
            new_name="background_image",
        ),
        migrations.RenameField(
            model_name="scheduledsocialpost",
            old_name="image_background",
            new_name="background_image",
        ),
    ]
