# Generated by Django 4.0.5 on 2022-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0018_alter_tweet_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('favorite_count', models.PositiveIntegerField()),
                ('twitter_id', models.PositiveIntegerField()),
                ('id_str', models.CharField(max_length=30)),
                ('retweet_count', models.PositiveIntegerField()),
                ('text', models.TextField(max_length=300)),
                ('twitter_url', models.URLField(null=True)),
                ('api_delete', models.BooleanField(default=False, help_text='It gets deleted from Twitter after clicking on Save', verbose_name='Delete from Twitter')),
                ('api_deleted', models.BooleanField(default=False, verbose_name='Already deleted from Twitter')),
            ],
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
