# Generated by Django 4.1 on 2022-09-04 16:03

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "socialmedia",
            "0019_rename_background_image_regularsocialpost_background_image_obj_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinpost",
            name="media_asset",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
