# Generated by Django 4.0.8 on 2022-11-03 20:35

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0020_linkedinpost_media_asset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialMediaPostedItem",
        ),
        migrations.AlterField(
            model_name="facebookpost",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted from Facebook after clicking on Save",
                verbose_name="Delete from Facebook",
            ),
        ),
        migrations.AlterField(
            model_name="instagrampost",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted from Instagram after clicking on Save",
                verbose_name="Delete from Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="linkedinpost",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted from Linkedin after clicking on Save",
                verbose_name="Delete from Linkedin",
            ),
        ),
        migrations.AlterField(
            model_name="telegrammessage",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted from Telegram after clicking on Save",
                verbose_name="Delete from Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="api_delete",
            field=models.BooleanField(
                default=False,
                help_text="It gets deleted from Twitter after clicking on Save",
                verbose_name="Delete from Twitter",
            ),
        ),
    ]
