# Generated by Django 4.0.8 on 2022-11-04 23:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0023_alter_regularsocialpost_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularsocialpost',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.AlterModelManagers(
            name='regularsocialpost',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduledSocialPost',
        ),
    ]
