# Generated by Django 4.0.8 on 2022-11-04 23:44

from __future__ import annotations

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socialmedia", "0023_alter_regularsocialpost_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regularsocialpost",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelManagers(
            name="regularsocialpost",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name="ScheduledSocialPost",
        ),
    ]
