# Generated by Django 4.2 on 2023-08-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0026_favoritetweetsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookPost',
        ),
        migrations.DeleteModel(
            name='FavoriteTweetSearch',
        ),
        migrations.DeleteModel(
            name='InstagramPost',
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='api_delete',
            field=models.BooleanField(default=False, verbose_name='Delete from Telegram'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='api_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted from Telegram'),
        ),
    ]
