# Generated by Django 4.2 on 2023-08-29 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0027_delete_facebookpost_delete_favoritetweetsearch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegularSocialPost',
            new_name='SocialPost',
        ),
    ]
