# Generated by Django 4.2 on 2023-08-29 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0028_rename_regularsocialpost_socialpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='background_image_obj',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='image_text',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='promote_in_facebook',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='promote_in_instagram',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='share_image',
        ),
        migrations.AddField(
            model_name='socialpost',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='socialposts/files/'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='promote_in_linkedin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='promote_in_telegram',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='promote_in_twitter',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
