# Generated by Django 4.2 on 2023-08-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0029_remove_socialpost_background_image_obj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpost',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='socialpost',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='image',
        ),
    ]
