# Generated by Django 4.2.4 on 2023-10-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0030_rename_created_socialpost_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='image_text',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
