# Generated by Django 4.2.4 on 2023-10-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0031_socialpost_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
