# Generated by Django 4.2.4 on 2023-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0034_socialpost_share_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='promote_in_facebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='promote_in_instagram',
            field=models.BooleanField(default=True),
        ),
    ]
