# Generated by Django 4.2.4 on 2023-10-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0036_rename_created_at_socialpost_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='background_image_obj',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='image_text',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='promote_in_facebook',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='promote_in_instagram',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='share_image',
        ),
    ]
