# Generated by Django 4.2.4 on 2023-10-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0037_remove_socialpost_background_image_obj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialpost',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='socialpost',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
