# Generated by Django 4.0.9 on 2023-02-28 18:04
import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import slugger.fields
from django.conf import settings
from django.db import migrations
from django.db import models

import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlexPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, null=True)),
                ("public", models.BooleanField(default=False)),
                ("slug", slugger.fields.AutoSlugField(populate_from="title")),
                ("content", markdownx.models.MarkdownxField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                (
                    "created_by",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flexpages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=250)),
                ("response", models.TextField(blank=True, max_length=250, null=True)),
                ("responded", models.BooleanField(default=False)),
                ("responded_on", models.DateField(blank=True, null=True)),
                (
                    "subscribe",
                    models.BooleanField(
                        default=False, verbose_name="Subscribe to our Newsletter"
                    ),
                ),
                ("subscribed", models.BooleanField(default=False)),
                ("created_on", models.DateField(auto_now_add=True)),
                (
                    "responded_by",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
