# Generated by Django 4.2.4 on 2023-10-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_flexpage_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryVisitor',
        ),
    ]
