# Generated by Django 4.2.4 on 2023-11-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_countryvisitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='views',
        ),
    ]
