# Generated by Django 4.0.8 on 2023-02-02 03:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookaffiliatelink",
            name="region",
        ),
        migrations.AddField(
            model_name="bookaffiliatelink",
            name="country_code",
            field=models.CharField(
                choices=[
                    ("US", "USA"),
                    ("DE", "Germany"),
                    ("ES", "Spain"),
                    ("FR", "France"),
                    ("IT", "Italy"),
                ],
                default="us",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookaffiliatelink",
            name="is_global",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookaffiliatelink",
            name="label",
            field=models.CharField(default="Dummy name", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "Not applicable"),
                    ("a1", "A1"),
                    ("a2", "A2"),
                    ("b1", "B1"),
                    ("b2", "B2"),
                    ("c1", "C1"),
                    ("c2", "C2"),
                ],
                default="b2",
                max_length=2,
                null=True,
            ),
        ),
    ]
