# Generated by Django 4.0.8 on 2023-02-02 21:13
import auto_prefetch
import django.db.models.deletion
from django.db import migrations
from django.db import models

import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0002_remove_bookaffiliatelink_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=markdownx.models.MarkdownxField(default="hello"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookaffiliatelink",
            name="book",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affiliate_links",
                to="affiliates.book",
            ),
        ),
    ]
