# Generated by Django 4.0.8 on 2023-02-02 21:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0003_book_content_book_image_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="content",
            new_name="description",
        ),
    ]
