# Generated by Django 4.0.8 on 2023-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_rename_content_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('text-book', 'Text book'), ('writing', 'Writing'), ('vocabulary', 'Vocabulary')], default='general', max_length=16),
        ),
        migrations.AddField(
            model_name='book',
            name='test_type',
            field=models.CharField(choices=[('general', 'General'), ('cambridge', 'Cambridge'), ('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('celpip', 'CELPIP')], default='general', max_length=16),
        ),
        migrations.AlterField(
            model_name='book',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very Basic'), (2, 'Basic'), (3, 'Intermediate'), (4, 'Intermediate-Advanced'), (5, 'Advanced'), (6, 'Very Advanced')], default=3),
        ),
    ]
