# Generated by Django 4.0.8 on 2023-02-04 11:10
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0005_book_category_book_test_type_alter_book_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General 📗"),
                    ("text-book", "Text books 📚"),
                    ("writing", "Writing 📝"),
                    ("vocabulary", "Vocabulary 👨\u200d\u200d🏫"),
                ],
                default="general",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("general", "General 🤓"),
                    ("cambridge", "Cambridge 💂\u200d♂️"),
                    ("ielts", "IELTS 🇬🇧"),
                    ("toefl", "TOEFL 🗽"),
                    ("celpip", "CELPIP 🏢"),
                ],
                default="general",
                max_length=16,
            ),
        ),
    ]
