# Generated by Django 4.0.8 on 2023-02-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0008_countryvisitor_alter_bookaffiliatelink_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryvisitor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countryvisitor',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
    ]
