# Generated by Django 4.0.9 on 2023-02-05 17:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0010_alter_book_name_alter_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
