# Generated by Django 4.2 on 2023-04-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0012_delete_countryvisitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('-views',)},
        ),
    ]
