# Generated by Django 4.2 on 2023-08-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0013_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='affiliate_disclosure',
            field=models.CharField(choices=[('amazon', 'As an Amazon Associate I earn from qualifying purchases.'), ('general', 'We will earn some commisions from this links')], default='amazon', max_length=16),
        ),
        migrations.AddField(
            model_name='book',
            name='affiliate_label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='affiliate_link',
            field=models.URLField(null=True),
        ),
    ]
