# Generated by Django 4.2 on 2023-08-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0014_book_affiliate_disclosure_book_affiliate_label_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAffiliateLink',
        ),
    ]
