# Generated by Django 4.2.4 on 2023-10-03 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0015_delete_bookaffiliatelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('label', models.CharField(max_length=64)),
                ('is_global', models.BooleanField(default=True)),
                ('country_code', models.CharField(max_length=8)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliates.book')),
            ],
        ),
    ]
