# Generated by Django 4.2.4 on 2023-11-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0018_remove_book_image_url_remove_book_thumbnail_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'base_manager_name': 'prefetch_manager'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
    ]
