# Generated by Django 4.0.4 on 2022-04-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
