# Generated by Django 4.0.5 on 2022-08-14 07:18

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_deepllanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="deepllanguage",
            name="formality",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
