# Generated by Django 4.0.3 on 2022-04-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_correct_answer_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
