# Generated by Django 4.1 on 2022-08-15 17:45

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_translatedquestion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deepllanguage",
            name="formality",
        ),
        migrations.AddField(
            model_name="deepllanguage",
            name="supports_formality",
            field=models.BooleanField(default=False),
        ),
    ]
