# Generated by Django 4.0.3 on 2022-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.IntegerField(choices=[(1, 'A1'), (2, 'A2'), (3, 'B1'), (4, 'B2'), (5, 'C1'), (6, 'C2')], default=5),
        ),
    ]
