# Generated by Django 4.1 on 2022-08-17 06:24

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_translatedquestion_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
