# Generated by Django 4.0.3 on 2022-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_name_question_text_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_three',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_two',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
