# Generated by Django 4.1 on 2022-09-03 07:10

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_alter_question_promoted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deepllanguage",
            options={"ordering": ["-views"]},
        ),
        migrations.AddField(
            model_name="deepllanguage",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
