# Generated by Django 4.0.3 on 2022-04-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_text_three_question_text_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, 'One choice selection'), (2, 'Multiple choice selection'), (3, 'Text input')], default=1),
        ),
    ]
