# Generated by Django 4.0.4 on 2022-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '1: One text input'), (2, '2: Two text input'), (5, '5: One choice selection'), (6, '6: Multiple choice selection')], default=1),
        ),
    ]
