# Generated by Django 4.0.8 on 2022-11-03 20:36
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_question_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="text_five",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
