# Generated by Django 4.0.4 on 2022-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_answer_name_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(default='----', max_length=128),
            preserve_default=False,
        ),
    ]
