# Generated by Django 4.0.8 on 2022-11-03 20:37
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0010_question_text_five"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="text_five",
        ),
    ]
