# Generated by Django 4.0.4 on 2022-05-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_answer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_one',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_three',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_two',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
