# Generated by Django 4.0.3 on 2022-05-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_question_text_one_alter_question_text_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, '1: One text input'), (2, '2: Two text input'), (5, '5: One choice selection'), (6, '6: Multiple choice selection')], default=1),
        ),
    ]
