# Generated by Django 4.0.8 on 2022-11-04 19:44
from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0011_remove_question_text_five"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="created_by",
        ),
    ]
