# Generated by Django 4.0.3 on 2022-05-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_lection_clicks_quiz_clicks_alter_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lection',
            old_name='clicks',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='clicks',
            new_name='views',
        ),
    ]
