# Generated by Django 4.0.4 on 2022-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_rename_clicks_lection_views_rename_clicks_quiz_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lection',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-views',)},
        ),
        migrations.AlterField(
            model_name='lection',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
