# Generated by Django 4.0.5 on 2022-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_lection_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='promote_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='promote_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
