# Generated by Django 4.0.5 on 2022-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_lection_promote_date_quiz_promote_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='promote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='promote',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
