# Generated by Django 4.0.5 on 2022-06-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_lection_promote_quiz_promote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='already_promoted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='already_promoted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
