# Generated by Django 4.2.4 on 2023-12-02 09:22

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_linkedin_posts', '0015_comment_poll_alter_comment_post_alter_comment_text'),
        ('quiz', '0018_alter_deepllanguage_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='linkedin_poll',
            field=auto_prefetch.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_linkedin_posts.poll'),
        ),
    ]
