# Generated by Django 4.0.5 on 2022-06-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_remove_lection_already_promoted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shared_in_linkedin',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='shared_in_telegram',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='shared_in_twitter',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
