# Generated by Django 4.0.5 on 2022-06-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_question_shared_in_linkedin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='shared_in_linkedin',
            new_name='shared_in_social_media',
        ),
        migrations.RemoveField(
            model_name='question',
            name='shared_in_telegram',
        ),
        migrations.RemoveField(
            model_name='question',
            name='shared_in_twitter',
        ),
    ]
