# Generated by Django 4.0.5 on 2022-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_rename_shared_in_linkedin_question_shared_in_social_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='promoted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='promoted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
