# Generated by Django 4.2.4 on 2023-12-02 10:52

import auto_prefetch
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_linkedin_posts', '0015_comment_poll_alter_comment_post_alter_comment_text'),
        ('quiz', '0020_question_linkedin_poll_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='linkedin_post',
            field=auto_prefetch.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_linkedin_posts.post'),
        ),
        migrations.AddField(
            model_name='question',
            name='linkedin_post_commented',
            field=models.BooleanField(default=False),
        ),
    ]
