# Generated by Django 4.2.4 on 2024-01-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_question_linkedin_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='linkedin_poll_commented',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='linkedin_post_commented',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
