# Generated by Django 4.0.5 on 2022-07-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_lection_promoted_quiz_promoted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='shared_in_social_media',
            new_name='promoted',
        ),
        migrations.RemoveField(
            model_name='lection',
            name='promote',
        ),
        migrations.RemoveField(
            model_name='lection',
            name='promote_date',
        ),
        migrations.RemoveField(
            model_name='lection',
            name='promoted',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='promote',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='promote_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='promoted',
        ),
    ]
