# Generated by Django 4.1 on 2022-08-21 19:04

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_contact_subscribe"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="responded_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
