# Generated by Django 4.1 on 2022-08-21 20:35

from __future__ import annotations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pages", "0006_contact_responded_on_contact_subscribed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="created",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="contact",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
