# Generated by Django 4.0.5 on 2022-08-09 22:20

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_post_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="status",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
