# Generated by Django 4.0.5 on 2022-08-10 21:54

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_author_blogpost_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="level",
            field=models.CharField(
                choices=[
                    ("elementary", "Elementary"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advamced"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
