# Generated by Django 4.0.5 on 2022-08-13 10:51

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogpost_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
