# Generated by Django 4.1 on 2022-08-15 15:47

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blogpost_created_alter_blogpost_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="level",
            field=models.CharField(
                choices=[
                    ("elementary", "Elementary"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
