# Generated by Django 4.1 on 2022-08-17 06:23

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogpost_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
