# Generated by Django 4.1 on 2022-08-18 06:01

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_blogpost_pdf_alter_blogpost_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="pdf_created",
            field=models.BooleanField(default=False),
        ),
    ]
