# Generated by Django 4.1 on 2022-08-18 06:12

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_blogpost_pdf_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="recreate_pdf",
            field=models.BooleanField(default=False),
        ),
    ]
