# Generated by Django 4.1 on 2022-08-18 06:13

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_blogpost_recreate_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="recreate_pdf",
        ),
    ]
