# Generated by Django 4.0.8 on 2022-11-10 19:53

import auto_prefetch
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_alter_blogpost_managers_alter_blogpost_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_by',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
