# Generated by Django 4.0.8 on 2022-11-12 08:58
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_blogpost_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="pdf_created",
            new_name="create_pdf",
        ),
    ]
