# Generated by Django 4.2 on 2023-04-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_pdf_created_blogpost_create_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ('-created',)},
        ),
    ]
