# Generated by Django 4.2 on 2023-08-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
    ]
