# Generated by Django 4.2.4 on 2023-11-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_blogpost_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='views',
        ),
    ]
