# Generated by Django 4.0.5 on 2022-07-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_linkedinpost_regularsocialpost_promote_in_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularsocialpost',
            name='image_text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scheduledsocialpost',
            name='image_text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='regularsocialpost',
            name='promote_in_facebook',
            field=models.BooleanField(default=False, verbose_name='Promote in Facebook'),
        ),
        migrations.AlterField(
            model_name='regularsocialpost',
            name='promote_in_instagram',
            field=models.BooleanField(default=False, verbose_name='Promote in Instagram'),
        ),
        migrations.AlterField(
            model_name='regularsocialpost',
            name='promote_in_linkedin',
            field=models.BooleanField(default=True, verbose_name='Promote in Linkedin'),
        ),
        migrations.AlterField(
            model_name='regularsocialpost',
            name='promote_in_telegram',
            field=models.BooleanField(default=True, verbose_name='Promote in Telegram'),
        ),
        migrations.AlterField(
            model_name='regularsocialpost',
            name='promote_in_twitter',
            field=models.BooleanField(default=True, verbose_name='Promote in Twitter'),
        ),
        migrations.AlterField(
            model_name='scheduledsocialpost',
            name='promote_in_facebook',
            field=models.BooleanField(default=False, verbose_name='Promote in Facebook'),
        ),
        migrations.AlterField(
            model_name='scheduledsocialpost',
            name='promote_in_instagram',
            field=models.BooleanField(default=False, verbose_name='Promote in Instagram'),
        ),
        migrations.AlterField(
            model_name='scheduledsocialpost',
            name='promote_in_linkedin',
            field=models.BooleanField(default=True, verbose_name='Promote in Linkedin'),
        ),
        migrations.AlterField(
            model_name='scheduledsocialpost',
            name='promote_in_telegram',
            field=models.BooleanField(default=True, verbose_name='Promote in Telegram'),
        ),
        migrations.AlterField(
            model_name='scheduledsocialpost',
            name='promote_in_twitter',
            field=models.BooleanField(default=True, verbose_name='Promote in Twitter'),
        ),
    ]
