# Generated by Django 4.0.5 on 2022-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0011_telegrammessage_api_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='api_delete',
            field=models.BooleanField(default=False, help_text='It gets deleted from Twitter after clicking on Save', verbose_name='Delete from Twitter'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='api_deleted',
            field=models.BooleanField(default=False, verbose_name='Already deleted from Twitter'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='api_delete',
            field=models.BooleanField(default=False, help_text='It gets deleted from Telegram after clicking on Save', verbose_name='Delete from Telegram'),
        ),
    ]
