# Generated by Django 4.0.5 on 2022-07-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0016_alter_tweet_favorite_count_alter_tweet_retweet_count_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tweet',
            table='tweets',
        ),
    ]
