# Generated by Django 4.0.5 on 2022-07-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0019_twitterpost_delete_tweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwitterPost',
            new_name='Tweet',
        ),
    ]
