# Generated by Django 4.0.5 on 2022-07-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0007_entrypagerelated_promote_in_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrypagerelated',
            name='promote_in_facebook',
        ),
        migrations.RemoveField(
            model_name='entrypagerelated',
            name='promote_in_instagram',
        ),
        migrations.RemoveField(
            model_name='entrypagerelated',
            name='promote_in_linkedin',
        ),
        migrations.RemoveField(
            model_name='entrypagerelated',
            name='promote_in_telegram',
        ),
        migrations.RemoveField(
            model_name='entrypagerelated',
            name='promote_in_twitter',
        ),
        migrations.AddField(
            model_name='entrypage',
            name='promote_in_facebook',
            field=models.BooleanField(default=True, verbose_name='Promote in Facebook'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='promote_in_instagram',
            field=models.BooleanField(default=True, verbose_name='Promote in Instagram'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='promote_in_linkedin',
            field=models.BooleanField(default=True, verbose_name='Promote in Linkedin'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='promote_in_telegram',
            field=models.BooleanField(default=True, verbose_name='Promote in Telegram'),
        ),
        migrations.AddField(
            model_name='entrypage',
            name='promote_in_twitter',
            field=models.BooleanField(default=True, verbose_name='Promote in Twitter'),
        ),
    ]
